puppycompanyblog/__init__.py
from flask import Flask

app = Flask(__name__)

from puppycompanyblog.core.views import core
from puppycompanyblog.error_pages.handlers import error_pages

app.register_blueprint(core)
app.register_blueprint(error_pages)

puppycompanyblog/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

puppycompanyblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Home Page</title>
</head>
<body>
    
    <!-- Nav Start -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{url_for('core.index')}}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('core.info')}}">About</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="#">Log Out</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Account</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Create Post</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="#">Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Register</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <!-- Nav End -->

    <div class="container-fluid">
        {% block content %}

        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

puppycompanyblog/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h1>Puppy Company Blog</h1>
    </div>
{% endblock %}

puppycompanyblog/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h1>About our company</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto at numquam dolore magni sapiente quibusdam, nesciunt nihil velit placeat iste voluptatibus ut fuga? Sapiente laudantium, magnam enim eaque adipisci soluta.</p>
    </div>
{% endblock %}